package eu.thechest.chestapi.maps;

/**
 * Created by zeryt on 28.05.2017.
 */
public enum MapLocationType {
    SPAWNPOINT,DM_VILLAGER_RED,DM_VILLAGER_BLUE,DM_VILLAGER_GREEN,INFW_MOBSPAWN,INFW_CHESTSPAWN,TK_TOBIKO,TK_SURVIVOR,SOCCER_RED_1,SOCCER_BLUE_1,SOCCER_RED_2,SOCCER_BLUE_2,SOCCER_RED_3,SOCCER_BLUE_3,SOCCER_RED_4,SOCCER_BLUE_4,SOCCER_CHICKEN,SOCCER_SPECTATOR
}
